version: '3'

services:

  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src/api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./docker/php
    container_name: "api"
    volumes:
      - ./src/api:/var/www

  mysql:
    image: mysql:5.7
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 13306:3306

  nuxt:
    build: 
      context: ./docker/nuxt/
    container_name: "app"
    privileged: true
    volumes:
      - "./src/app:/usr/share/nginx/html"
    ports:
      - 3000:3000
